app/reservations/forms.py
from flask_wtf import FlaskForm
from wtforms import (DateField, IntegerField, SelectField, StringField,
                     SubmitField, TextAreaField)
from wtforms.validators import DataRequired, InputRequired, Length, NumberRange

from .models import StatusEnum

STATUS_CHOICES = [(status.name, status.value) for status in StatusEnum]


class ServiceForm(FlaskForm):
    title = StringField(
        'Название услуги',
        validators=[DataRequired(message='Обязательное поле'),
                    Length(1, 100)]
    )
    price = IntegerField(
        'Стоимость одной услуги',
        validators=[
            InputRequired('Обязательное поле'),
            NumberRange(
                min=0,
                message='Введите неотрицательное число'
            )]
    )
    submit = SubmitField('Добавить')


class ServiceUpdateForm(ServiceForm):
    submit = SubmitField('Сохранить изменения')


class OrderForm(FlaskForm):
    name = StringField(
        'Имя гостя',
        validators=[DataRequired(message='Обязательное поле'),
                    Length(1, 100)]
    )
    guests_count = IntegerField(
        'Количество гостей',
        validators=[
            InputRequired(message='Обязательное поле'),
            NumberRange(
                min=0,
                message='Введите неотрицательное число'
            )]
    )
    guides_count = IntegerField(
        'Количество гидов',
        validators=[
            InputRequired(message='Обязательное поле'),
            NumberRange(
                min=0,
                message='Введите неотрицательное число'
            )
            ]
    )
    checkin_date = DateField(
        'Дата заезда (ГГГГ-ММ-ДД)',
        format='%Y-%m-%d',
        validators=[DataRequired(message='Обязательное поле')]
    )
    checkout_date = DateField(
        'Дата выезда (ГГГГ-ММ-ДД)',
        format='%Y-%m-%d',
        validators=[DataRequired(message='Обязательное поле')]
    )
    price = IntegerField(
        'Стоимость одной ночи',
        validators=[
            InputRequired('Обязательное поле'),
            NumberRange(
                min=0,
                message='Введите неотрицательное число'
            )
        ]
    )
    comment = TextAreaField('Комментарий')
    submit = SubmitField('Создать')


class OrderUpdateForm(OrderForm):
    status = SelectField(
        'Статус', choices=STATUS_CHOICES,
        validators=[DataRequired(message='Обязательное поле')]
    )
    submit = SubmitField('Сохранить изменения')


class OrderServiceForm(FlaskForm):
    service = SelectField('Дополнительная услуга', validators=[DataRequired()])
    quantity = IntegerField(
        'Количество',
        validators=[
            InputRequired('Обязательное поле'),
            NumberRange(
                min=0,
                message='Введите неотрицательное число'
            )
        ]
    )
    submit = SubmitField('Сохранить')


class SalaryDateForm(FlaskForm):
    start_date = DateField(
        'Начальная дата (ГГГГ-ММ-ДД)',
        format='%Y-%m-%d',
        validators=[DataRequired(message='Обязательное поле')]
    )
    finish_date = DateField(
        'Конечная дата (ГГГГ-ММ-ДД)',
        format='%Y-%m-%d',
        validators=[DataRequired(message='Обязательное поле')]
    )
    submit = SubmitField('Рассчитать')

    def validate(self):
        if not super().validate():
            return False
        if self.start_date.data >= self.finish_date.data:
            self.start_date.errors.append(
                'Начальная дата должна быть раньше конечной даты'
            )
            return False
        return True

app/reservations/__init__.py
from flask import Blueprint

reservations_bp = Blueprint('reservations', __name__)

from . import models, routes

app/reservations/routes.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flask_paginate import get_page_parameter
from sqlalchemy import desc
from sqlalchemy.exc import IntegrityError

from .. import db, logger
from ..constants import ITEMS_PER_PAGE
from . import reservations_bp
from .forms import (OrderForm, OrderServiceForm, OrderUpdateForm,
                    SalaryDateForm, ServiceForm, ServiceUpdateForm)
from .models import Order, OrderService, Service, StatusEnum


@reservations_bp.route('/')
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    orders = (Order.query
              .filter_by(status=StatusEnum.CREATED)
              .order_by(Order.checkin_date)
              .paginate(page, ITEMS_PER_PAGE, error_out=False))
    return render_template('reservations/index.html', orders=orders)


@reservations_bp.route('/orders-all')
@login_required
def orders_all():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    orders = (Order.query
              .order_by(desc(Order.checkout_date))
              .paginate(page, ITEMS_PER_PAGE, error_out=False))
    return render_template('reservations/orders_all.html', orders=orders)


@reservations_bp.route('/order/<int:id>', methods=['GET', 'POST'])
@login_required
def order_detail(id):
    order = Order.query.get_or_404(id)
    form = OrderServiceForm()
    services = Service.query.filter_by(active=True).order_by('title').all()
    form.service.choices = [
        (str(service.id), f'{service.title} - {service.price} сом')
        for service in services
    ]

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                service_id = int(form.service.data)
                quantity = form.quantity.data

                order_service = OrderService.query.filter_by(
                    order_id=id,
                    service_id=service_id
                ).first()

                if order_service:
                    if quantity == 0:
                        db.session.delete(order_service)
                        logger.info(
                            f'Юзер {current_user.email} удалил из заказа '
                            f'{id=} услугу {service_id=}'
                        )
                        flash('Дополнительная услуга успешно удалена',
                              'order-success')
                    else:
                        order_service.quantity = quantity
                        logger.info(
                            f'Юзер {current_user.email} обновил в заказе '
                            f'{id=} количество услуги {service_id=} - '
                            f'{quantity} шт'
                        )
                        flash('Дополнительная услуга успешно обновлена',
                              'order-success')
                else:
                    order_service = OrderService(
                        order_id=id,
                        service_id=service_id,
                        quantity=quantity,
                    )
                    db.session.add(order_service)
                    logger.info(
                        f'Юзер {current_user.email} добавил к заказу {id=} '
                        f'услугу {service_id=} в количестве {quantity} шт'
                    )
                    flash('Дополнительная услуга успешно добавлена',
                          'order-success')

                db.session.commit()

                return redirect(url_for('reservations.order_detail', id=id))
            except Exception as e:
                db.session.rollback()
                logger.error(f'Ошибка при обновлении заказа {id=}:\n'
                             f'{str(e)}')
                flash('Ошибка при обновлении заказа', 'order-error')

    return render_template('reservations/order_detail.html',
                           order=order, form=form)


@reservations_bp.route('/order-create', methods=['GET', 'POST'])
@login_required
def order_create():
    form = OrderForm()

    if form.validate_on_submit():
        try:
            order = Order(
                name=form.name.data,
                guests_count=form.guests_count.data,
                guides_count=form.guides_count.data,
                checkin_date=form.checkin_date.data,
                checkout_date=form.checkout_date.data,
                price=form.price.data,
                comment=form.comment.data,
            )
            db.session.add(order)
            db.session.commit()
            logger.info(f'Юзер {current_user.email} создал заказ с данными:\n'
                        f'{form.data}')
            flash('Заказ успешно создан!', 'order-success')
            return redirect(url_for('reservations.order_detail', id=order.id))
        except IntegrityError as e:
            db.session.rollback()
            logger.error(f'Ошибка IntegrityError при создании заказа:\n'
                         f'{str(e)}')
            flash('Заказ с таким именем и датами уже существует.',
                  'order-error')
        except Exception as e:
            db.session.rollback()
            logger.error(f'Ошибка при создании заказа:\n'
                         f'{str(e)}')
            flash('Ошибка при создании заказа', 'order-error')

    return render_template('reservations/order_create.html', form=form)


@reservations_bp.route('/order-update/<int:id>', methods=['GET', 'POST'])
@login_required
def order_update(id):
    order = Order.query.get_or_404(id)
    form = OrderUpdateForm(obj=order)

    if form.validate_on_submit():
        try:
            form.populate_obj(order)
            db.session.commit()
            logger.info(f'Юзер {current_user.email} обновил заказ {id=} '
                        f'данными:\n{form.data}')
            flash('Заказ успешно обновлен!', 'order-success')
            return redirect(url_for('reservations.order_detail', id=order.id))
        except Exception as e:
            db.session.rollback()
            logger.error(f'Ошибка при обновлении заказа {id=}:\n'
                         f'{str(e)}')
            flash('Ошибка при обновлении заказа', 'order-error')

    return render_template('reservations/order_update.html',
                           form=form, order_id=id)


@reservations_bp.route('/service-create', methods=['GET', 'POST'])
@login_required
def service_create():
    form = ServiceForm()

    if form.validate_on_submit():
        try:
            service = Service(
                title=form.title.data,
                price=form.price.data,
            )
            db.session.add(service)
            db.session.commit()
            logger.info(f'Юзер {current_user.email} создал услугу с данными:\n'
                        f'{form.data}')
            flash('Услуга успешно создана!', 'service-success')
            return redirect(url_for('reservations.services_list'))
        except IntegrityError as e:
            db.session.rollback()
            logger.error(f'Ошибка при создании услуги:\n'
                         f'{str(e)}')
            flash('Услуга с таким названием уже существует',
                  'service-error')

    return render_template('reservations/service_create.html', form=form)


@reservations_bp.route('/services-list')
@login_required
def services_list():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    services = (Service.query
                .filter_by(active=True)
                .order_by('title')
                .paginate(page, ITEMS_PER_PAGE, error_out=False))
    return render_template('reservations/services_list.html',
                           services=services)


@reservations_bp.route('/services-archive')
@login_required
def services_archive():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    services = (Service.query
                .filter_by(active=False)
                .paginate(page, ITEMS_PER_PAGE, error_out=False))
    return render_template('reservations/services_archive.html',
                           services=services)


@reservations_bp.route('/service-update/<int:id>', methods=['GET', 'POST'])
@login_required
def service_update(id):
    service = Service.query.get_or_404(id)
    form = ServiceUpdateForm(obj=service)

    if form.validate_on_submit():
        try:
            form.populate_obj(service)
            db.session.commit()
            logger.info(f'Юзер {current_user.email} обновил услугу {id=} '
                        f'данными:\n{form.data}')
            flash('Услуга успешно обновлена!', 'service-success')
            return redirect(url_for('reservations.services_list'))
        except IntegrityError as e:
            db.session.rollback()
            logger.error(f'Ошибка при обновлении услуги {id=}:\n'
                         f'{str(e)}')
            flash('Услуга с таким названием уже существует',
                  'service-error')

    return render_template('reservations/service_update.html',
                           form=form, service_id=id)


@reservations_bp.route('/service-delete/<int:id>')
@login_required
def service_delete(id):
    service = Service.query.get_or_404(id)

    try:
        service.active = False
        db.session.commit()
        logger.info(f'Юзер {current_user.email} удалил услугу {id=}')
        flash('Услуга успешно удалена!', 'service-success')
        return redirect(url_for('reservations.services_archive'))
    except Exception as e:
        db.session.rollback()
        logger.error(f'Ошибка при удалении услуги {id=}:\n'
                     f'{str(e)}')
        flash('Ошибка при удалении услуги', 'service-error')
        return redirect(url_for('reservations.services_list'))


@reservations_bp.route('/service-restore/<int:id>')
@login_required
def service_restore(id):
    service = Service.query.get_or_404(id)

    try:
        service.active = True
        db.session.commit()

app/templates/reservations/index.html
{% extends 'partials/base.html' %}

{% block title %}Главная страница{% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>{% block main_text %}Предстоящие бронирования{% endblock main_text %}</h1>
  <a href="{{ url_for('reservations.order_create') }}" class="btn btn-primary">Добавить бронирование</a>
</div>

{% if orders.items %}
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Имя гостя</th>
        <th scope="col">Дата заезда</th>
        <th scope="col">Дата выезда</th>
        <th scope="col">Ночей</th>
        <th scope="col">Гостей</th>
        <th scope="col">Коментарий</th>
        <th scope="col">Статус</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders.items %}
      <tr>
        <td>{{ order.id }}</td>
        <td>{{ order.name }}</td>
        <td>{{ order.checkin_date }}</td>
        <td>{{ order.checkout_date }}</td>
        <td>{{ order.days_count }}</td>
        <td>{{ order.guests_count }}</td>
        <td>{{ order.comment[:40] }}...</td>
        <td>{{ order.status.value }}</td>
        <td><a href="{{ url_for('reservations.order_detail', id=order.id) }}" class="text-dark">Детали</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% block paginator %}
    {% if orders.has_prev %}
      <a href="{{ url_for('reservations.index', page=orders.prev_num) }}" class="btn btn-outline-primary">&laquo; Предыдущая</a>
    {% else %}
      <span class="btn btn-outline-secondary disabled">&laquo; Предыдущая</span>
    {% endif %}

    {% if orders.has_next %}
      <a href="{{ url_for('reservations.index', page=orders.next_num) }}" class="btn btn-outline-primary">Следующая &raquo;</a>
    {% else %}
      <span class="btn btn-outline-secondary disabled">Следующая &raquo;</span>
    {% endif %}
  {% endblock paginator %}

{% else %}
  <p>Пока нет ни одного бронирования</p>
{% endif %}

{% endblock content %}

app/templates/reservations/order_create.html
{% extends 'partials/base.html' %}

{% block title %}Создание бронирования{% endblock title %}

{% block content %}

<h1 class="mb-3">Создать новое бронирование</h1>

{% with messages = get_flashed_messages(category_filter=["order-error"]) %}
  {% if messages %}
    {% for message in messages %}
      <p style="color: red">
        {{ message }}
      </p>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="col-12 col-lg-7">
  <form method="POST" novalidate>
    {{ form.csrf_token }}
    {{ form.name(class="form-control form-control-lg", placeholder=form.name.label.text) }}
    <p>
      {% if form.name.errors %}
        {% for error in form.name.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.guests_count(class="form-control form-control-lg", placeholder=form.guests_count.label.text) }}
    <p>
      {% if form.guests_count.errors %}
        {% for error in form.guests_count.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.guides_count(class="form-control form-control-lg", placeholder=form.guides_count.label.text) }}
    <p>
      {% if form.guides_count.errors %}
        {% for error in form.guides_count.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.checkin_date(class="form-control form-control-lg", placeholder=form.checkin_date.label.text) }}
    <p>
      {% if form.checkin_date.errors %}
        {% for error in form.checkin_date.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.checkout_date(class="form-control form-control-lg", placeholder=form.checkout_date.label.text) }}
    <p>
      {% if form.checkout_date.errors %}
        {% for error in form.checkout_date.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.price(class="form-control form-control-lg", placeholder=form.price.label.text) }}
    <p>
      {% if form.price.errors %}
        {% for error in form.price.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.comment(class="form-control form-control-lg", placeholder=form.comment.label.text, rows="3", cols="40") }}
    <p></p>
    {{ form.submit(class="btn btn-lg btn-primary") }}
  </form>
</div>

{% endblock content %}

app/templates/reservations/order_detail.html
{% extends 'partials/base.html' %}

{% block title %}Подробности бронирования{% endblock title %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <h1 class="mb-3">
      {% block main_text %}Бронирование №{{ order.id }}{% endblock main_text %}
    </h1>

    {% with messages = get_flashed_messages(category_filter=["order-success"]) %}
      {% if messages %}
        {% for message in messages %}
          <p style="color: green">
            {{ message }}
          </p>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% with messages = get_flashed_messages(category_filter=["order-error"]) %}
      {% if messages %}
        {% for message in messages %}
          <p style="color: red">
            {{ message }}
          </p>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <ul class="list-unstyled">
      <li class="text-start">Имя гостя: {{ order.name }}</li>
      <li>Дата заезда: {{ order.checkin_date }}</li>
      <li>Дата выезда: {{ order.checkout_date }}</li>
      <li>Количество гостей: {{ order.guests_count }}</li>
      <li>
        {% if order.guides_count %}
          Количество гидов: {{ order.guides_count }}
        {% endif %}
      </li>
      <li>Количество ночей: {{ order.days_count }}</li>
      <li>Стоимость одного места: {{ order.price }}</li>
      {% if order.comment %}
        <li class="text-break">Комментарий: {{ order.comment }}</li>
      {% endif %}
      <li>Статус: {{ order.status }}</li>
      <li><b>Полная стоимость: {{ order.total_price }}</b></li>
    </ul>
    <a href="{{ url_for('reservations.order_update', id=order.id) }}" class="btn btn-lg btn-primary">Редактировать</a>
  </div>

  <div class="col-md-6">
    <h4>Допуслуги в бронировании №{{ order.id }}:</h4>
    {% if order.services %}
      <ul class="list-unstyled">
        {% for service in order.services %}
          <li>"{{ service.service.title }}" {{ service.service.price }} сом - {{ service.quantity }} шт.</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Пока добавленных услуг нет</p>
    {% endif %}
    <h4>Добавить/редактировать услугу:</h4>
    <form method="post" novalidate>
      {{ form.csrf_token }}

      {{ form.service(class="form-control form-control-lg", placeholder=form.service.label.text) }}
      <br>
      {{ form.quantity(class="form-control form-control-lg", placeholder=form.quantity.label.text) }}
      <p>
        {% if form.quantity.errors %}
          {% for error in form.quantity.errors %}
            <span style="color: red">{{ error }}</span>
          {% endfor %}
        {% endif %}
      </p>
      {{ form.submit(class="btn btn-lg btn-primary") }}
    </form>
  </div>
</div>

{% endblock content %}

app/templates/reservations/order_update.html
{% extends 'partials/base.html' %}

{% block title %}Редактирование бронирования{% endblock title %}

{% block content %}

<h1 class="mb-3">Редактировать бронирование №{{ order_id }}</h1>

{% with messages = get_flashed_messages(category_filter=["order-error"]) %}
  {% if messages %}
    {% for message in messages %}
      <p style="color: red">
        {{ message }}
      </p>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="col-12 col-lg-7">
  <form method="POST" novalidate>
    {{ form.csrf_token }}
    {{ form.name(class="form-control form-control-lg", placeholder=form.name.label.text) }}
    <p>
      {% if form.name.errors %}
        {% for error in form.name.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.guests_count(class="form-control form-control-lg", placeholder=form.guests_count.label.text) }}
    <p>
      {% if form.guests_count.errors %}
        {% for error in form.guests_count.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.guides_count(class="form-control form-control-lg", placeholder=form.guides_count.label.text) }}
    <p>
      {% if form.guides_count.errors %}
        {% for error in form.guides_count.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.checkin_date(class="form-control form-control-lg", placeholder=form.checkin_date.label.text) }}
    <p>
      {% if form.checkin_date.errors %}
        {% for error in form.checkin_date.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.checkout_date(class="form-control form-control-lg", placeholder=form.checkout_date.label.text) }}
    <p>
      {% if form.checkout_date.errors %}
        {% for error in form.checkout_date.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.price(class="form-control form-control-lg", placeholder=form.price.label.text) }}
    <p>
      {% if form.price.errors %}
        {% for error in form.price.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.status(class="form-control form-control-lg", placeholder=form.status.label.text) }}
    <p>
      {% if form.status.errors %}
        {% for error in form.status.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.comment(class="form-control form-control-lg", placeholder=form.comment.label.text, rows="3", cols="40") }}
    <p></p>
    {{ form.submit(class="btn btn-lg btn-primary") }}
  </form>
</div>

{% endblock content %}

app/templates/reservations/orders_all.html
{% extends 'reservations/index.html' %}

{% block title %}Все бронирования{% endblock title %}
{% block main_text %}Список всех бронирований{% endblock main_text %}

{% block paginator %}
  {% if orders.has_prev %}
    <a href="{{ url_for('reservations.orders_all', page=orders.prev_num) }}" class="btn btn-outline-primary">&laquo; Предыдущая</a>
  {% else %}
    <span class="btn btn-outline-secondary disabled">&laquo; Предыдущая</span>
  {% endif %}

  {% if orders.has_next %}
    <a href="{{ url_for('reservations.orders_all', page=orders.next_num) }}" class="btn btn-outline-primary">Следующая &raquo;</a>
  {% else %}
    <span class="btn btn-outline-secondary disabled">Следующая &raquo;</span>
  {% endif %}
{% endblock paginator %}

app/templates/reservations/service_update.html
{% extends 'reservations/service_create.html' %}

{% block title %}Редактирование услуги{% endblock title %}
{% block main_text %}Редактировать услугу №{{ service_id }}{% endblock main_text %}

app/templates/reservations/services_archive.html
{% extends 'partials/base.html' %}

{% block title %}Архив услуг{% endblock title %}

{% block content %}

<h1 class="mb-3">Список неактивных услуг</h1>
{% with messages = get_flashed_messages(category_filter=["service-success"]) %}
	{% if messages %}
	  {% for message in messages %}
		  <p style="color: green">
		    {{ message }}
		  </p>
	  {% endfor %}
	{% endif %}
{% endwith %}
{% with messages = get_flashed_messages(category_filter=["service-error"]) %}
	{% if messages %}
	  {% for message in messages %}
		  <p style="color: red">
		    {{ message }}
		  </p>
	  {% endfor %}
	{% endif %}
{% endwith %}

{% if services.items %}
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Название</th>
        <th scope="col">Стоимость</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for service in services.items %}
      <tr>
        <td>{{ service.id }}</td>
        <td>{{ service.title }}</td>
        <td>{{ service.price }}</td>
        <td><a href="{{ url_for('reservations.service_restore', id=service.id) }}" class="text-dark">Восстановить</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if services.has_prev %}
    <a href="{{ url_for('reservations.services_archive', page=services.prev_num) }}" class="btn btn-outline-primary">&laquo; Предыдущая</a>
  {% else %}
    <span class="btn btn-outline-secondary disabled">&laquo; Предыдущая</span>
  {% endif %}

  {% if services.has_next %}
    <a href="{{ url_for('reservations.services_archive', page=services.next_num) }}" class="btn btn-outline-primary">Следующая &raquo;</a>
  {% else %}
    <span class="btn btn-outline-secondary disabled">Следующая &raquo;</span>
  {% endif %}

{% else %}
  <p>Пока нет ни одной неактивной допуслуги</p>
{% endif %}

{% endblock content %}

app/templates/reservations/services_list.html
{% extends 'partials/base.html' %}

{% block title %}Все услуги{% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>Список всех услуг</h1>
  <div>
    <a href="{{ url_for('reservations.service_create') }}" class="btn btn-primary">Добавить услугу</a>
    <a href="{{ url_for('reservations.services_archive') }}" class="btn btn-outline-primary">Архив услуг</a>
  </div>
</div>

{% with messages = get_flashed_messages(category_filter=["service-success"]) %}
	{% if messages %}
	  {% for message in messages %}
		  <p style="color: green">
		    {{ message }}
		  </p>
	  {% endfor %}
	{% endif %}
{% endwith %}
{% with messages = get_flashed_messages(category_filter=["service-error"]) %}
	{% if messages %}
	  {% for message in messages %}
		  <p style="color: red">
		    {{ message }}
		  </p>
	  {% endfor %}
	{% endif %}
{% endwith %}

{% if services.items %}
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Название</th>
        <th scope="col">Стоимость</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for service in services.items %}
      <tr>
        <td>{{ service.id }}</td>
        <td>{{ service.title }}</td>
        <td>{{ service.price }}</td>
        <td><a href="{{ url_for('reservations.service_update', id=service.id) }}" class="text-dark">Редактировать</a></td>
        <td><a href="{{ url_for('reservations.service_delete', id=service.id) }}" class="text-dark">Удалить</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if services.has_prev %}
    <a href="{{ url_for('reservations.services_list', page=services.prev_num) }}" class="btn btn-outline-primary">&laquo; Предыдущая</a>
  {% else %}
    <span class="btn btn-outline-secondary disabled">&laquo; Предыдущая</span>
  {% endif %}

  {% if services.has_next %}
    <a href="{{ url_for('reservations.services_list', page=services.next_num) }}" class="btn btn-outline-primary">Следующая &raquo;</a>
  {% else %}
    <span class="btn btn-outline-secondary disabled">Следующая &raquo;</span>
  {% endif %}

{% else %}
  <p>Пока нет ни одной допуслуги</p>
{% endif %}

{% endblock content %}