app/cash/models.py
from enum import StrEnum

from sqlalchemy.orm import validates

from .. import db


class TransactionType(StrEnum):
    ACCOMMODATION = 'Проживание'
    EXTRA_SERVICES = 'Допуслуги'
    BAR_PAYMENT = 'Из бара'
    SALARY = 'Зарплата'
    OPERATING_COSTS = 'Операционные расходы'
    WITHDRAWAL = 'Изъятие средств'
    ELSE = 'Другое'


class Transaction(db.Model):
    __tablename__ = 'transactions'

    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False)
    debit = db.Column(db.Integer)
    credit = db.Column(db.Integer)
    type = db.Column(db.Enum(TransactionType), nullable=False)
    comment = db.Column(db.Text)

    @classmethod
    def cash_balance(cls):
        transactions = cls.query.all()
        total_credit = sum(
            transaction.credit
            for transaction in transactions
            if transaction.credit is not None
        )
        total_debit = sum(
            transaction.debit
            for transaction in transactions
            if transaction.debit is not None
        )
        return total_debit - total_credit

    @validates('debit', 'credit')
    def validate_positive(self, key, value):
        if value is not None and value <= 0:
            raise ValueError(f'{key} должно быть положительным')
        return value

    def __repr__(self):
        amount = 'приход' if self.credit != 0 else 'расход'
        return (
            f'Транзакция {self.id} ({self.date}), '
            f'{amount}={self.debit or self.credit}, '
            f'тип - {self.type}'
        )

app/cash/forms.py
from flask_wtf import FlaskForm
from wtforms import (DateField, IntegerField, SelectField, SubmitField,
                     TextAreaField)
from wtforms.validators import DataRequired, NumberRange, Optional

from .models import TransactionType

TYPE_CHOICES = [(type.name, type.value) for type in TransactionType]


class TransactionForm(FlaskForm):
    date = DateField(
        'Дата транзакции (ГГГГ-ММ-ДД)',
        format='%Y-%m-%d',
        validators=[DataRequired(message='Обязательное поле')]
    )
    debit = IntegerField(
        'Приход',
        validators=[
            Optional(),
            NumberRange(
                min=1,
                message='Введите положительное число'
            )
        ]
    )
    credit = IntegerField(
        'Расход',
        validators=[
            Optional(),
            NumberRange(
                min=1,
                message='Введите положительное число'
            )
        ]
    )
    type = SelectField(
        'Тип транзакции', choices=TYPE_CHOICES,
        validators=[DataRequired(message='Обязательное поле')]
    )
    comment = TextAreaField('Комментарий')
    submit = SubmitField('Сохранить')

    def validate(self):
        if not super().validate():
            return False

        if self.debit.data is None and self.credit.data is None:
            self.debit.errors.append(
                'Поле "Приход" или "Расход" должно быть заполнено'
            )
            self.credit.errors.append(
                'Поле "Приход" или "Расход" должно быть заполнено'
            )
            return False
        elif self.debit.data is not None and self.credit.data is not None:
            self.debit.errors.append(
                'Заполните только одно из полей "Приход" или "Расход"'
            )
            self.credit.errors.append(
                'Заполните только одно из полей "Приход" или "Расход"'
            )
            return False

        return True

app/cash/__init__.py
from flask import Blueprint

cash_bp = Blueprint('cash', __name__)

from . import models, routes

app/cash/routes.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flask_paginate import get_page_parameter
from sqlalchemy import desc

from .. import db, logger
from ..constants import ITEMS_PER_PAGE
from . import cash_bp
from .forms import TransactionForm
from .models import Transaction


@cash_bp.route('/transactions-list')
@login_required
def transactions_list():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    transactions = (Transaction.query
                    .order_by(desc(Transaction.date))
                    .paginate(page, ITEMS_PER_PAGE, error_out=False))
    cash_balance = Transaction.cash_balance()
    return render_template('cash/transactions_list.html',
                           transactions=transactions,
                           cash_balance=cash_balance)


@cash_bp.route('/transaction-create', methods=['GET', 'POST'])
@login_required
def transaction_create():
    form = TransactionForm()

    if form.validate_on_submit():
        try:
            transaction = Transaction(
                date=form.date.data,
                debit=form.debit.data,
                credit=form.credit.data,
                type=form.type.data,
                comment=form.comment.data,
            )
            db.session.add(transaction)
            db.session.commit()
            logger.info(f'Юзер {current_user.email} создал транзакцию '
                        f'с данными:\n{form.data}')
            flash('Транзакция успешно создана!', 'cash-success')
            return redirect(url_for('cash.transactions_list'))
        except ValueError as e:
            db.session.rollback()
            logger.error(f'Ошибка при создании транзакции:\n'
                         f'{str(e)}')
            flash('Ошибка при создании транзакции', 'cash-error')

    return render_template('cash/transaction_create.html', form=form)


@cash_bp.route('/transaction-update/<int:id>', methods=['GET', 'POST'])
@login_required
def transaction_update(id):
    transaction = Transaction.query.get_or_404(id)
    form = TransactionForm(obj=transaction)

    if form.validate_on_submit():
        try:
            form.populate_obj(transaction)
            db.session.commit()
            logger.info(f'Юзер {current_user.email} обновил транзакцию {id=} '
                        f'данными:\n{form.data}')
            flash('Транзакция успешно обновлена!', 'cash-success')
            return redirect(url_for('cash.transactions_list'))
        except ValueError as e:
            db.session.rollback()
            logger.error(f'Ошибка при обновлении транзакции {id=}:\n'
                         f'{str(e)}')
            flash(f'Ошибка при обновлении транзакции: {str(e)}', 'cash-error')

    return render_template('cash/transaction_update.html',
                           form=form, transaction_id=id)


@cash_bp.route('/transaction-delete/<int:id>')
@login_required
def transaction_delete(id):
    transaction = Transaction.query.get_or_404(id)

    try:
        db.session.delete(transaction)
        db.session.commit()
        logger.info(f'Юзер {current_user.email} удалил транзакцию {id=}')
        flash('Транзакция успешно удалена!', 'cash-success')
    except Exception as e:
        db.session.rollback()
        logger.error(f'Ошибка при удалении транзакции {id=}: {str(e)}')
        flash('Ошибка при удалении транзакции', 'cash-error')

    return redirect(url_for('cash.transactions_list'))

app/templates/cash/transaction_create.html
{% extends 'partials/base.html' %}

{% block title %}Создание транзакции{% endblock title %}

{% block content %}

<h1 class="mb-3">
  {% block main_text %}Создать новую транзакцию{% endblock main_text %}
</h1>

{% with messages = get_flashed_messages(category_filter=["cash-error"]) %}
  {% if messages %}
    {% for message in messages %}
      <p style="color: red">
        {{ message }}
      </p>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="col-12 col-lg-7">
  <form method="POST" novalidate>
    {{ form.csrf_token }}
    {{ form.date(class="form-control form-control-lg", placeholder=form.date.label.text) }}
    <p>
      {% if form.date.errors %}
        {% for error in form.date.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.debit(class="form-control form-control-lg", placeholder=form.debit.label.text) }}
    <p>
      {% if form.debit.errors %}
        {% for error in form.debit.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.credit(class="form-control form-control-lg", placeholder=form.credit.label.text) }}
    <p>
      {% if form.credit.errors %}
        {% for error in form.credit.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.type(class="form-control form-control-lg", placeholder=form.type.label.text) }}
    <p>
      {% if form.type.errors %}
        {% for error in form.type.errors %}
          <span style="color: red">{{ error }}</span>
        {% endfor %}
      {% endif %}
    </p>
    {{ form.comment(class="form-control form-control-lg", placeholder=form.comment.label.text, rows="3", cols="40") }}
    <p></p>
    {{ form.submit(class="btn btn-lg btn-primary") }}
  </form>
</div>

{% endblock content %}

app/templates/cash/transaction_update.html
{% extends 'cash/transaction_create.html' %}

{% block title %}Редактирование транзакции{% endblock title %}
{% block main_text %}Редактировать транзакцию №{{ transaction_id }}{% endblock main_text %}

app/templates/cash/transactions_list.html
{% extends 'partials/base.html' %}

{% block title %}Касса{% endblock title %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>{% block main_text %}Основная касса{% endblock main_text %}</h1>
  <a href="{{ url_for('cash.transaction_create') }}" class="btn btn-primary">Добавить транзакцию</a>
</div>

{% with messages = get_flashed_messages(category_filter=["cash-success"]) %}
  {% if messages %}
    {% for message in messages %}
      <p style="color: green">
        {{ message }}
      </p>
    {% endfor %}
  {% endif %}
{% endwith %}

{% with messages = get_flashed_messages(category_filter=["cash-error"]) %}
  {% if messages %}
    {% for message in messages %}
      <p style="color: red">
        {{ message }}
      </p>
    {% endfor %}
  {% endif %}
{% endwith %}

<p><b>Остаток в кассе: {{ cash_balance }}</b></p>

{% if transactions.items %}
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Дата</th>
        <th scope="col">Приход</th>
        <th scope="col">Расход</th>
        <th scope="col">Тип транзакции</th>
        <th scope="col">Коментарий</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions.items %}
      <tr>
        <td>{{ transaction.id }}</td>
        <td>{{ transaction.date }}</td>
        <td>
          {% if transaction.debit %}
            {{ transaction.debit }}
          {% else %}
            ...
          {% endif %}
        </td>
        <td>
          {% if transaction.credit %}
            {{ transaction.credit }}
          {% else %}
            ...
          {% endif %}
        </td>
        <td>{{ transaction.type }}</td>
        <td>{{ transaction.comment }}...</td>
        <td><a href="{{ url_for('cash.transaction_update', id=transaction.id) }}" class="text-dark">Редактировать</a></td>
        <td><a href="{{ url_for('cash.transaction_delete', id=transaction.id) }}" class="text-dark">Удалить</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% block paginator %}
    {% if transactions.has_prev %}
      <a href="{{ url_for('cash.transactions_list', page=transactions.prev_num) }}" class="btn btn-outline-primary">&laquo; Предыдущая</a>
    {% else %}
      <span class="btn btn-outline-secondary disabled">&laquo; Предыдущая</span>
    {% endif %}

    {% if transactions.has_next %}
      <a href="{{ url_for('cash.transactions_list', page=transactions.next_num) }}" class="btn btn-outline-primary">Следующая &raquo;</a>
    {% else %}
      <span class="btn btn-outline-secondary disabled">Следующая &raquo;</span>
    {% endif %}
  {% endblock paginator %}

{% else %}
  <p>Пока нет ни одной транзакции</p>
{% endif %}

{% endblock content %}